### ISSUE TITLE
non-descript error message on user-stupidity

### ISSUE THREAD

**Issue by Bijaelo** [teunbrand/ggnomics#10]
Following your latter example in [this question](https://stackoverflow.com/a/55911134/10782538), but failing to use the correct data (eg. using the [question](https://stackoverflow.com/q/40316169/10782538) provided data), throws a very unhelpful error. 

>Error in vapply(missing, var_list, character(1)) : 
>  object 'var_list' not found

Adding an error check for var_list in the function [combine_nested_vars](https://github.com/teunbrand/ggnomics/blob/master/R/facet_nested.R) would be wonderful.

**Comment by Bijaelo** [comment]
I've sat with it a bit now. 

The error occurs (on my end) when a variable name typed does not exist, eg. if one used `Nester` rather than `nester` in `facet_nested` in the help page example.

If the user spells this incorrectly, `combine_nested_vars` runs into the above mentioned error, due to the lack of the `var_list` function.

The user is returned with the "var_list not found" error message. 

### Minimum reproducible example
```R
df <- iris
df$nester <- ifelse(df$Species == "setosa",
                    "Short Leaves",
                    "Long Leaves")

ggplot(df, aes(Sepal.Length, Petal.Length)) +
    geom_point() +
    facet_nested(~ Nester + Species)
```


Ps. There seems to be a minor spelling mistake at the same point in the code:

```R
if (!any(has_all)) {
        missing <- lapply(values, function(x) setdiff(names(vars), 
            names(x)))
        missing_txt <- vapply(missing, var_list, character(1))
        name <- c("Plot", paste0("Layer ", seq_len(length(data) - 
            1)))
        stop("At least one lyaer must contain all faceting variables: ",  #### <== spelling error in fourth word. Should be Layer
            var_list(names(vars)), ".\n", paste0("* ", 
                name, " is missing", missing_txt, collapse = "\n"), 
            call. = FALSE)
    }
```

**Comment by teunbrand** [comment]
Hi, thank you for finding this inelegant error handling (and spelling error!). The trouble was that `var_list()` was a ggplot2 internal function and I had forgotten to call it as `ggplot2:::var_list()`. I've fixed that now, and after the next push, the function should return the same error as `facet_grid()`. I also added a test to check for error messages.

**Comment by Bijaelo** [comment]
Thanks for making this available. It will be a very useful function, throughout my thesis. :-)
