### ISSUE TITLE
Bioconductor dependencies

### ISSUE THREAD

**Issue by Bijaelo** [teunbrand/ggnomics#11]
Currently the package seems to contain 3 dependencies from Bioconductor

1. AnnotationDbi
2. GenomeInfoDb
3. GenomicFeatures

Installing these are a bit of a frustration, so adding these to the front page, might prove helpful? 
[The very last reply on this devtools issue](https://github.com/r-lib/devtools/issues/700) seems to mention something about adding `bioViews: (pkgs)` to the description.

**Comment by teunbrand** [comment]
That is a good suggestion. Probably there are even more packages from bioconductor that this repository depends on implicitly. I'll add it to the description and it should be there the next time I push to github!

**Comment by teunbrand** [comment]
I found one potential downside of this, and that is that `sessioninfo::sessioninfo()` (and thus also `devtools::sessioninfo()`) lists the package's source as Bioconductor, which should be github. I'm thinking about going for the `try_require()` method that ggplot2 and ggforce use for specific functions, and then moving the bioconductor dependencies from imports to suggests.

**Comment by teunbrand** [comment]
I think I might have fixed this, so I'm closing this for now. If this should be a problem in the future, please open a new issue.
