### ISSUE TITLE
Error in FUN(X[[i]], ...) : unused argument (env = env)

### ISSUE THREAD

**Issue by maximilian-heeg** [teunbrand/ggnomics#37]
Hi,

with a recent update to ggplot2, there was a change to the function eval_facets().
![image](https://user-images.githubusercontent.com/38260677/76347168-658b6380-62c3-11ea-892c-0c62c6efd713.png)

https://github.com/tidyverse/ggplot2/commit/5e6b1e5daa1599661bf5841353a067e9eee88161#diff-b8cdc3f131782de7db4bd9302d590821

The arguement _env_ is no longer supported. This causes an error when using facet_nested(). A few changes in facet_nested.R might solve these errors:

![image](https://user-images.githubusercontent.com/38260677/76347429-dcc0f780-62c3-11ea-8440-c19b8f7a093b.png)

Thanks for this wonderful package.
Max

**Comment by teunbrand** [comment]
Hi Max, thanks for letting me know.

I'm reorganising this package a bit to separate out the genomics related versus not genomics related functionality so I can shamelessly gorge myself on Bioconductor dependencies in ggnomics in the future. 
`facet_nested()` and most other non-genomics functions have found a new home at the [ggh4x](https://github.com/teunbrand/ggh4x) package, which I've tested against/adjusted for ggplot v3.3.0.
If you'd like to use the `facet_nested()` function, I recommend to use the one from the other package.

Best wishes,
Teun

**Comment by maximilian-heeg** [comment]
Hi, 

thanks for your fast answer. That totally solves my problem.

Best wishes,
max
