### ISSUE TITLE
Example not working: Error in FUN(X[[i]], ...): unused argument (env = env)

### ISSUE THREAD

**Issue by tungttnguyen** [teunbrand/ggnomics#38]
Hello,

I tried the posted example but it didn't work. Can you check what went wrong?

Thanks for this pretty cool package! 

``` r

library(tidyverse, warn.conflicts = FALSE)
library(ggnomics)

phi <- 2/(1 + sqrt(5))

df <- iris
df$nester <- ifelse(df$Species == "setosa",
                    "Short Leaves",
                    "Long Leaves")

g <- ggplot(df, aes(x = Sepal.Length, y = Petal.Length)) +
  geom_point(aes(sepal.width = Sepal.Width),
             ggsubset(Species == "setosa")) +
  geom_point(aes(petal.length = Petal.Length),
             ggsubset(Species == "versicolor")) +
  geom_point(aes(petal.width = Petal.Width),
             ggsubset(Species == "virginica")) +
  facet_nested(~ nester + Species, scales = "free")
#> Warning: Ignoring unknown aesthetics: sepal.width
#> Warning: Ignoring unknown aesthetics: petal.length
#> Warning: Ignoring unknown aesthetics: petal.width
g
#> Error in FUN(X[[i]], ...): unused argument (env = env)
```

![](https://i.imgur.com/FpfsEpj.png)

<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tungttnguyen** [comment]
btw I'm using 

`ggplot2     * 3.3.0.9000  2020-03-23 [1] Github (tidyverse/ggplot2@53815f8) `

**Comment by teunbrand** [comment]
Hi there,

I know that the facet_nested is not working (see #37), this is largely because I've moved the function to another package as I'm in the process of reshaping ggnomics to be more about genomics.
My recommendation is to use the ggh4x package for facet_nested instead.

Best wishes

**Comment by tungttnguyen** [comment]
Thanks for the info!
